apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxjava-gateway-example
  labels:
    app: rxjava-gateway-example
spec:
  replicas: 1
  template:
    metadata:
      name: rxjava-gateway-example
      labels:
        app: rxjava-gateway-example
    spec:
      containers:
        - name: rxjava-gateway-example
          image: registry.cn-shanghai.aliyuncs.com/taro-mall/rxjava-gateway-example:latest
          imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: rxjava-gateway-example
---
apiVersion: v1
kind: Service
metadata:
  name: rxjava-gateway-example
spec:
  selector:
    app: rxjava-gateway-example
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort